name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install_dependencies
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: build linux
      run: make linux_build
